apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql-volume
  name: mysql-volume
spec:
  containers:
  - image: mysql
    name: mysql
    ports:
        - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eazy
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: data-volume 
  volumes:
  - name: data-volume
    hostPath: 
      path: /data-volume
      type: DirectoryOrCreate

      
