apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql-pv
  name: mysql-pv
spec:
  containers:
  - image: mysql
    name: mysql
    ports:
        - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eazy
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: pv-claim


      
