apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simple-webapp-color
  name: simple-webapp-color
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    name: simple-webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: red
